//! NoNpDrm licenses: the fixed-layout `work.bin` / `*.rif` record, and the
//! zRIF text form that packs the same record as base64 over a deflate stream
//! using a fixed preset dictionary.

use std::path::Path;

use anyhow::{Context, Result, bail};
use base64::Engine as _;
use flate2::{Decompress, FlushDecompress};
use serde::{Deserialize, Serialize};

/// Size of a PS Vita application or add-on license record.
pub const RIF_SIZE: usize = 0x200;
/// Size of a PSM license record.
pub const PSM_RIF_SIZE: usize = 0x400;

/// Account id NoNpDrm stamps into the licenses it generates.
const FAKE_AID: u64 = 0x0123_4567_89AB_CDEF;

const CONTENT_ID_OFFSET: usize = 0x10;
const CONTENT_ID_LEN: usize = 0x30;
const KLICENSEE_OFFSET: usize = 0x50;
const KLICENSEE_LEN: usize = 0x10;

/// Adler-32 of [`zrif_dict`], which is also the dictionary id a zRIF stream
/// carries in its zlib header.
const ZRIF_DICT_ID: u32 = 0x627D_1D5D;
const ZRIF_DICT_LEN: usize = 1024;

/// Trailing bytes of the zRIF preset dictionary; everything before them is
/// zero. See [`zrif_dict`].
#[rustfmt::skip]
const ZRIF_DICT_TAIL: [u8; 144] = [
    0x30, 0x30, 0x30, 0x30, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x30, 0x30, 0x30, 0x30, 0x36, 0x30, 0x30, 0x30,
    0x30, 0x37, 0x30, 0x30, 0x30, 0x30, 0x38, 0x00, 0x30, 0x30, 0x30, 0x30,
    0x33, 0x30, 0x30, 0x30, 0x30, 0x34, 0x30, 0x30, 0x30, 0x30, 0x35, 0x30,
    0x5f, 0x30, 0x30, 0x2d, 0x41, 0x44, 0x44, 0x43, 0x4f, 0x4e, 0x54, 0x30,
    0x30, 0x30, 0x30, 0x32, 0x2d, 0x50, 0x43, 0x53, 0x47, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x31, 0x2d, 0x50, 0x43, 0x53,
    0x45, 0x30, 0x30, 0x30, 0x2d, 0x50, 0x43, 0x53, 0x46, 0x30, 0x30, 0x30,
    0x2d, 0x50, 0x43, 0x53, 0x43, 0x30, 0x30, 0x30, 0x2d, 0x50, 0x43, 0x53,
    0x44, 0x30, 0x30, 0x30, 0x2d, 0x50, 0x43, 0x53, 0x41, 0x30, 0x30, 0x30,
    0x2d, 0x50, 0x43, 0x53, 0x42, 0x30, 0x30, 0x30, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x01, 0x00, 0x02, 0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01,
];

/// Where the license came from, as told by its account id.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LicenseKind {
    /// Generated by NoNpDrm, which stamps a fixed sentinel account id.
    NoNpDrmFake,
    /// Issued to a real account.
    Retail,
}

/// Fields read from a license record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoNpDrmInfo {
    pub content_id: String,
    pub kind: LicenseKind,
    pub version: u16,
    pub version_flag: u16,
    pub license_type: u16,
    pub license_flags: u16,
    pub account_id: u64,
    pub sku_flag: Option<u32>,
    /// True when the klicensee block at 0x50 is not all zero.
    pub has_klicensee: bool,
}

/// The zRIF preset dictionary, whose leading 880 bytes are zero.
fn zrif_dict() -> [u8; ZRIF_DICT_LEN] {
    let mut dict = [0u8; ZRIF_DICT_LEN];
    dict[ZRIF_DICT_LEN - ZRIF_DICT_TAIL.len()..].copy_from_slice(&ZRIF_DICT_TAIL);
    dict
}

/// Reads a `work.bin` or `.rif` license file from `path`.
pub fn read_info(path: &Path) -> Result<NoNpDrmInfo> {
    let data =
        std::fs::read(path).with_context(|| format!("nonpdrm info: read {}", path.display()))?;
    parse(&data).with_context(|| format!("nonpdrm info: parse {}", path.display()))
}

/// Reads the content id and klicensee a `work.bin` or `.rif` license
/// carries; the klicensee is the key the content's PFS layer is encrypted
/// under.
///
/// # Errors
/// Returns an error if the file cannot be read, is not a license record,
/// or carries an all-zero (absent) klicensee.
pub fn read_license_key(path: &Path) -> Result<(String, [u8; 16])> {
    use std::io::Read;

    // Bounded read: only the fixed record head is needed, and license
    // discovery may probe neighbouring files of arbitrary size.
    let mut head = [0u8; RIF_SIZE];
    std::fs::File::open(path)
        .and_then(|mut f| f.read_exact(&mut head))
        .with_context(|| format!("nonpdrm klicensee: read {}", path.display()))?;
    let info = parse(&head)?;
    if !info.has_klicensee {
        bail!("nonpdrm: license {} carries no klicensee", path.display());
    }
    let key = head[KLICENSEE_OFFSET..KLICENSEE_OFFSET + KLICENSEE_LEN]
        .try_into()
        .expect("16-byte slice");
    Ok((info.content_id, key))
}

/// Parses a license record. Accepts the application and PSM record sizes.
pub fn parse(data: &[u8]) -> Result<NoNpDrmInfo> {
    if data.len() < RIF_SIZE {
        bail!(
            "nonpdrm: license is {} bytes, expected at least {RIF_SIZE}",
            data.len()
        );
    }

    let raw = &data[CONTENT_ID_OFFSET..CONTENT_ID_OFFSET + CONTENT_ID_LEN];
    let end = raw.iter().position(|&b| b == 0).unwrap_or(raw.len());
    let content_id = String::from_utf8_lossy(&raw[..end]).into_owned();

    let account_id = u64::from_le_bytes(data[8..16].try_into().expect("8-byte slice"));
    let klicensee = &data[KLICENSEE_OFFSET..KLICENSEE_OFFSET + KLICENSEE_LEN];

    Ok(NoNpDrmInfo {
        content_id,
        kind: if account_id == FAKE_AID {
            LicenseKind::NoNpDrmFake
        } else {
            LicenseKind::Retail
        },
        version: be_u16(data, 0x00),
        version_flag: be_u16(data, 0x02),
        license_type: be_u16(data, 0x04),
        license_flags: be_u16(data, 0x06),
        account_id,
        sku_flag: (data.len() >= 0x100).then(|| be_u32(data, 0xFC)),
        has_klicensee: klicensee.iter().any(|&b| b != 0),
    })
}

/// Decodes a zRIF string back into the license record it packs.
pub fn decode_zrif(zrif: &str) -> Result<Vec<u8>> {
    let stripped: String = zrif.chars().filter(|c| !c.is_ascii_whitespace()).collect();
    let raw = base64::engine::general_purpose::STANDARD_NO_PAD
        .decode(stripped.trim_end_matches('='))
        .context("nonpdrm: zRIF is not valid base64")?;

    // RFC 1950 header, then a deflate stream over the preset dictionary,
    // then the Adler-32 of the decompressed record.
    if raw.len() < 6 + 4 {
        bail!("nonpdrm: zRIF is too short");
    }
    if (u16::from(raw[0]) << 8 | u16::from(raw[1])) % 31 != 0 {
        bail!("nonpdrm: zRIF header is corrupted");
    }
    if raw[0] & 0x0F != 8 {
        bail!("nonpdrm: zRIF uses an unsupported compression method");
    }
    if raw[1] & 0x20 == 0 {
        bail!("nonpdrm: zRIF is missing its preset dictionary flag");
    }
    if be_u32(&raw, 2) != ZRIF_DICT_ID {
        bail!("nonpdrm: zRIF uses an unknown dictionary");
    }

    let body = &raw[6..raw.len() - 4];
    let expected = be_u32(&raw, raw.len() - 4);

    let mut inflate = Decompress::new(false);
    inflate
        .set_dictionary(&zrif_dict())
        .context("nonpdrm: cannot install the zRIF dictionary")?;
    let mut out = Vec::with_capacity(PSM_RIF_SIZE);
    inflate
        .decompress_vec(body, &mut out, FlushDecompress::Finish)
        .context("nonpdrm: cannot decompress zRIF")?;

    if adler32(&out) != expected {
        bail!("nonpdrm: zRIF checksum mismatch");
    }
    Ok(out)
}

fn adler32(data: &[u8]) -> u32 {
    let (mut a, mut b) = (1u32, 0u32);
    for &byte in data {
        a = (a + u32::from(byte)) % 65521;
        b = (b + a) % 65521;
    }
    (b << 16) | a
}

fn be_u16(d: &[u8], off: usize) -> u16 {
    u16::from_be_bytes(d[off..off + 2].try_into().expect("2-byte slice"))
}

fn be_u32(d: &[u8], off: usize) -> u32 {
    u32::from_be_bytes(d[off..off + 4].try_into().expect("4-byte slice"))
}

#[cfg(test)]
mod tests {
    use super::*;

    const CONTENT_ID: &str = "EP9000-PCSF00001_00-EXAMPLE000000000";

    fn rif(account_id: u64, klicensee: bool) -> Vec<u8> {
        let mut out = vec![0u8; RIF_SIZE];
        out[0x00..0x02].copy_from_slice(&1u16.to_be_bytes());
        out[0x02..0x04].copy_from_slice(&1u16.to_be_bytes());
        out[0x04..0x06].copy_from_slice(&1u16.to_be_bytes());
        out[0x06..0x08].copy_from_slice(&2u16.to_be_bytes());
        out[0x08..0x10].copy_from_slice(&account_id.to_le_bytes());
        out[CONTENT_ID_OFFSET..CONTENT_ID_OFFSET + CONTENT_ID.len()]
            .copy_from_slice(CONTENT_ID.as_bytes());
        if klicensee {
            out[KLICENSEE_OFFSET..KLICENSEE_OFFSET + KLICENSEE_LEN].copy_from_slice(&[0x5A; 16]);
        }
        out[0xFC..0x100].copy_from_slice(&3u32.to_be_bytes());
        out
    }

    /// The zlib dictionary id is the Adler-32 of the dictionary, so this
    /// proves the embedded bytes are the real zRIF dictionary.
    #[test]
    fn dictionary_matches_its_published_id() {
        assert_eq!(adler32(&zrif_dict()), ZRIF_DICT_ID);
    }

    #[test]
    fn parses_a_nonpdrm_fake_license() {
        let info = parse(&rif(FAKE_AID, true)).unwrap();
        assert_eq!(info.content_id, CONTENT_ID);
        assert_eq!(info.kind, LicenseKind::NoNpDrmFake);
        assert_eq!(info.account_id, FAKE_AID);
        assert_eq!(info.version, 1);
        assert_eq!(info.license_type, 1);
        assert_eq!(info.license_flags, 2);
        assert_eq!(info.sku_flag, Some(3));
        assert!(info.has_klicensee);
    }

    #[test]
    fn parses_a_retail_license_without_klicensee() {
        let info = parse(&rif(0x1122_3344_5566_7788, false)).unwrap();
        assert_eq!(info.kind, LicenseKind::Retail);
        assert_eq!(info.account_id, 0x1122_3344_5566_7788);
        assert!(!info.has_klicensee);
    }

    #[test]
    fn rejects_a_short_license() {
        assert!(parse(&[0u8; 64]).is_err());
    }

    #[test]
    fn zrif_roundtrips_through_the_preset_dictionary() {
        use flate2::{Compress, Compression, FlushCompress};

        let want = rif(FAKE_AID, true);
        let mut deflate = Compress::new(Compression::best(), true);
        deflate.set_dictionary(&zrif_dict()).unwrap();
        let mut packed = Vec::with_capacity(4096);
        deflate
            .compress_vec(&want, &mut packed, FlushCompress::Finish)
            .unwrap();

        let text = base64::engine::general_purpose::STANDARD.encode(&packed);
        assert_eq!(decode_zrif(&text).unwrap(), want);
    }

    #[test]
    fn rejects_zrif_with_a_foreign_dictionary_id() {
        use flate2::{Compress, Compression, FlushCompress};

        let mut deflate = Compress::new(Compression::best(), true);
        deflate.set_dictionary(&[0xAAu8; 64]).unwrap();
        let mut packed = Vec::with_capacity(4096);
        deflate
            .compress_vec(&rif(FAKE_AID, true), &mut packed, FlushCompress::Finish)
            .unwrap();

        let text = base64::engine::general_purpose::STANDARD.encode(&packed);
        let err = decode_zrif(&text).unwrap_err().to_string();
        assert!(err.contains("unknown dictionary"), "{err}");
    }

    #[test]
    fn rejects_non_base64_zrif() {
        assert!(decode_zrif("not valid base64 !!!").is_err());
    }
}
