import { useCtrVerifyStore } from "~/stores/ctr-verify";
import { useDolVerifyStore } from "~/stores/dol-verify";
import { useRvlVerifyStore } from "~/stores/rvl-verify";
import { useWupVerifyStore } from "~/stores/wup-verify";
import { useNxVerifyStore } from "~/stores/nx-verify";
import { useChdVerifyStore } from "~/stores/chd-verify";
import { useCsoVerifyStore } from "~/stores/cso-verify";
import { registerOp } from "./types";

const SUBTITLE = "Checks hashes and container structure. Read-only.";
const DROP_TEXT = "Drop files or a folder";
const ACTION_NOTE = "Verify jobs run in the global queue too. Results appear below as they finish.";

registerOp("verify", {
	ctr: {
		op: "verify",
		console: "ctr",
		opLabel: "ctr verify",
		storeId: "ctr-verify",
		useStore: useCtrVerifyStore,
		command: "cmd_verify_ctr",
		resultKind: "verify",
		progressKey: "ctr-verify",
		title: "Verify 3DS files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["cia", "3ds", "cci", "cxi", "zcia", "zcci", "zcxi", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [
			{ name: "3DS ROM", extensions: ["cia", "3ds", "cci", "cxi", "zcia", "zcci", "zcxi", "zip", "7z", "rar", "tar", "tgz", "gz"] },
		],
		fields: [
			{
				kind: "toggle",
				key: "verifyContent",
				label: "Verify content hashes",
				description: "Also check SHA-256 hashes of all content data (CIA only, slower)",
			},
		],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, verifyContent: !!store.verifyContent }),
		chips: (store) => (store.verifyContent ? "content hashes" : "structure only"),
	},
	dol: {
		op: "verify",
		console: "dol",
		opLabel: "dol verify",
		storeId: "dol-verify",
		useStore: useDolVerifyStore,
		command: "cmd_verify_dol",
		resultKind: "verify",
		progressKey: "dol-verify",
		title: "Verify GameCube files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["iso", "gcm", "rvz", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [{ name: "GameCube disc", extensions: ["iso", "gcm", "rvz", "zip", "7z", "rar", "tar", "tgz", "gz"] }],
		fields: [{ kind: "toggle", key: "full", label: "Full verification" }],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, full: !!store.full }),
		chips: (store) => (store.full ? "full verification" : "quick"),
	},
	rvl: {
		op: "verify",
		console: "rvl",
		opLabel: "rvl verify",
		storeId: "rvl-verify",
		useStore: useRvlVerifyStore,
		command: "cmd_verify_rvl",
		resultKind: "verify",
		progressKey: "rvl-verify",
		title: "Verify Wii files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["iso", "wbfs", "rvz", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [{ name: "Wii disc", extensions: ["iso", "wbfs", "rvz", "zip", "7z", "rar", "tar", "tgz", "gz"] }],
		fields: [{ kind: "toggle", key: "full", label: "Full verification" }],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, full: !!store.full }),
		chips: (store) => (store.full ? "full verification" : "quick"),
	},
	wup: {
		op: "verify",
		console: "wup",
		opLabel: "wup verify",
		storeId: "wup-verify",
		useStore: useWupVerifyStore,
		command: "cmd_wup_verify",
		resultKind: "verify",
		progressKey: "wup-verify",
		title: "Verify Wii U files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["wud", "wux", "wua", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [{ name: "Wii U disc images", extensions: ["wud", "wux", "wua", "zip", "7z", "rar", "tar", "tgz", "gz"] }],
		browseAlsoDirectory: true,
		fields: [
			{
				kind: "file",
				key: "keys",
				label: "Disc master key file (optional, for .wud/.wux inputs only)",
				filters: [{ name: "Disc key", extensions: ["key", "bin", "txt"] }],
				display: (store) => store.keys || "none",
			},
		],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, keys: store.keys || null }),
		chips: (store) => (store.keys ? "disc key set" : "no disc key"),
	},
	nx: {
		op: "verify",
		console: "nx",
		opLabel: "nx verify",
		storeId: "nx-verify",
		useStore: useNxVerifyStore,
		command: "cmd_nx_verify",
		resultKind: "verify",
		progressKey: "nx-verify",
		title: "Verify Switch files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["nsp", "nsz", "xci", "xcz", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [
			{ name: "Switch container", extensions: ["nsp", "nsz", "xci", "xcz", "zip", "7z", "rar", "tar", "tgz", "gz"] },
		],
		fields: [
			{
				kind: "file",
				key: "keys",
				label: "prod.keys",
				filters: [{ name: "prod.keys", extensions: ["keys", "txt"] }],
				display: (store) => store.keys || "none",
			},
		],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, keys: store.keys || null }),
		chips: (store) => (store.keys ? "prod.keys set" : "no prod.keys"),
	},
	chd: {
		op: "verify",
		console: "chd",
		opLabel: "chd verify",
		storeId: "chd-verify",
		useStore: useChdVerifyStore,
		command: "cmd_chd_verify",
		resultKind: "verify",
		progressKey: "chd-verify",
		title: "Verify CD / DVD (CHD) files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["chd", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [{ name: "CHD", extensions: ["chd", "zip", "7z", "rar", "tar", "tgz", "gz"] }],
		fields: [
			{
				kind: "file",
				key: "parent",
				label: "Parent CHD (optional)",
				filters: [{ name: "CHD", extensions: ["chd"] }],
				display: (store) => store.parent || "none",
			},
			{ kind: "toggle", key: "fix", label: "Fix SHA-1", description: "Automatically fix incorrect SHA-1 values in the header" },
		],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ input: item.path, parent: store.parent || null, fix: !!store.fix }),
		chips: (store) => {
			const parts = [];
			if (store.parent) parts.push("parent set");
			if (store.fix) parts.push("fix sha-1");
			return parts.length ? parts.join(" · ") : "default";
		},
	},
	cso: {
		op: "verify",
		console: "cso",
		opLabel: "cso verify",
		storeId: "cso-verify",
		useStore: useCsoVerifyStore,
		command: "cmd_cso_verify",
		resultKind: "verify",
		progressKey: "cso-verify",
		title: "Verify PSP / PS2 files",
		subtitle: SUBTITLE,
		dropText: DROP_TEXT,
		acceptedExts: ["cso", "zso", "dax", "zip", "7z", "rar", "tar", "tgz", "gz"],
		browseFilters: [{ name: "Compressed ISO", extensions: ["cso", "zso", "dax", "zip", "7z", "rar", "tar", "tgz", "gz"] }],
		fields: [
			{
				kind: "toggle",
				key: "full",
				label: "Full verification",
				description: "Decode every block instead of only checking the index",
			},
		],
		outputRows: [],
		showConflict: false,
		showVerify: false,
		showDryRun: false,
		actionNote: ACTION_NOTE,
		deriveOutput: undefined,
		buildArgs: (store, item) => ({ inputPath: item.path, full: !!store.full }),
		chips: (store) => (store.full ? "full verification" : "quick"),
	},
});
