//! Two-character publisher / maker code lookup shared across all
//! Nintendo platforms (GameCube, Wii, Wii U, 3DS, DS, Switch).
//!
//! Table ported from Dolphin's `Source/Core/DiscIO/Enums.cpp`
//! `GetCompanyFromID` map (MIT licensed). Lookup is case-insensitive.

pub fn lookup_maker(code: &str) -> Option<&'static str> {
    let bytes = code.as_bytes();
    if bytes.len() != 2 {
        return None;
    }
    let upper = [bytes[0].to_ascii_uppercase(), bytes[1].to_ascii_uppercase()];
    Some(match &upper {
        b"01" => "Nintendo",
        b"02" => "Nintendo",
        b"08" => "Capcom",
        b"0A" => "Jaleco / Jaleco Entertainment",
        b"0L" => "Warashi",
        b"0M" => "Entertainment Software Publishing",
        b"0Q" => "IE Institute",
        b"13" => "Electronic Arts Japan",
        b"18" => "Hudson Soft / Hudson Entertainment",
        b"1K" => "Titus Software",
        b"20" => "DSI Games / ZOO Digital Publishing",
        b"28" => "Kemco Japan",
        b"29" => "SETA Corporation",
        b"2K" => "NEC Interchannel",
        b"2L" => "Agatsuma Entertainment",
        b"2M" => "Jorudan",
        b"2N" => "Smilesoft / Rocket Company",
        b"2Q" => "MediaKite",
        b"36" => "Codemasters",
        b"41" => "Ubisoft",
        b"4F" => "Eidos Interactive",
        b"4Q" => "Disney Interactive Studios / Buena Vista Games",
        b"4Z" => "Crave Entertainment / Red Wagon Games",
        b"51" => "Acclaim Entertainment",
        b"52" => "Activision",
        b"54" => "Take-Two Interactive / GameTek / Rockstar Games / Global Star Software",
        b"5D" => "Midway Games / Tradewest",
        b"5G" => "Majesco Entertainment",
        b"5H" => "3DO / Global Star Software",
        b"5L" => "NewKidCo",
        b"5S" => "Evolved Games / Xicat Interactive",
        b"5V" => "Agetec",
        b"5Z" => "Data Design / Conspiracy Entertainment",
        b"60" => "Titus Interactive / Titus Software",
        b"64" => "LucasArts",
        b"68" => "Bethesda Softworks / Mud Duck Productions / Vir2L Studios",
        b"69" => "Electronic Arts",
        b"6E" => "Sega",
        b"6K" => "UFO Interactive Games",
        b"6L" => "BAM! Entertainment",
        b"6M" => "System 3",
        b"6N" => "Midas Interactive Entertainment",
        b"6S" => "TDK Mediactive",
        b"6U" => "The Adventure Company / DreamCatcher Interactive",
        b"6V" => "JoWooD Entertainment",
        b"6W" => "Sega",
        b"6X" => "Wanadoo Edition",
        b"6Z" => "NDS Software",
        b"70" => "Atari (Infogrames)",
        b"71" => "Interplay Entertainment",
        b"75" => "SCi Games",
        b"78" => "THQ / Play THQ",
        b"7D" => "Sierra Entertainment / Vivendi Games / Universal Interactive Studios",
        b"7F" => "Kemco",
        b"7G" => "Rage Software",
        b"7H" => "Encore Software",
        b"7J" => "Zushi Games / ZOO Digital Publishing",
        b"7K" => "Kiddinx Entertainment",
        b"7L" => "Simon & Schuster Interactive",
        b"7M" => "Badland Games",
        b"7N" => "Empire Interactive / Xplosiv",
        b"7S" => "Rockstar Games",
        b"7T" => "Scholastic",
        b"7U" => "Ignition Entertainment",
        b"82" => "Namco",
        b"8G" => "NEC Interchannel",
        b"8J" => "Kadokawa Shoten",
        b"8M" => "CyberFront",
        b"8N" => "Success",
        b"8P" => "Sega",
        b"91" => "Chunsoft",
        b"99" => "Marvelous Entertainment / Victor Entertainment / Pack-In-Video / Rising Star Games",
        b"9B" => "Tecmo",
        b"9G" => "Take-Two Interactive / Global Star Software / Gotham Games / Gathering of Developers",
        b"9S" => "Brother International",
        b"9Z" => "Crunchyroll",
        b"A4" => "Konami",
        b"A7" => "Takara",
        b"AF" => "Namco Bandai Games",
        b"AU" => "Alternative Software",
        b"AX" => "Vivendi",
        b"B0" => "Acclaim Japan",
        b"B2" => "Bandai Games",
        b"BB" => "Sunsoft",
        b"BL" => "MTO",
        b"BM" => "XING",
        b"BN" => "Sunrise Interactive",
        b"BP" => "Global A Entertainment",
        b"C0" => "Taito",
        b"C8" => "Koei",
        b"CM" => "Konami Computer Entertainment Osaka",
        b"CQ" => "From Software",
        b"D9" => "Banpresto",
        b"DA" => "Tomy / Takara Tomy",
        b"DQ" => "Compile Heart / Idea Factory",
        b"E5" => "Epoch",
        b"E6" => "Game Arts",
        b"E7" => "Athena",
        b"E8" => "Asmik Ace Entertainment",
        b"E9" => "Natsume",
        b"EB" => "Atlus",
        b"EL" => "Spike",
        b"EM" => "Konami Computer Entertainment Tokyo",
        b"EP" => "Sting Entertainment",
        b"ES" => "Starfish-SD",
        b"EY" => "Vblank Entertainment",
        b"FH" => "Easy Interactive",
        b"FJ" => "Virtual Toys",
        b"FK" => "The Game Factory",
        b"FP" => "Mastiff",
        b"FR" => "Digital Tainment Pool",
        b"FS" => "XS Games",
        b"G0" => "Alpha Unit",
        b"G2" => "Yuke's",
        b"G6" => "SIMS",
        b"G9" => "D3 Publisher",
        b"GA" => "PIN Change",
        b"GD" => "Square Enix",
        b"GE" => "Kids Station",
        b"GG" => "O3 Entertainment",
        b"GJ" => "Detn8 Games",
        b"GK" => "Genki",
        b"GL" => "Gameloft / Ubisoft",
        b"GM" => "Gamecock Media Group",
        b"GN" => "Oxygen Games",
        b"GR" => "GSP",
        b"GT" => "505 Games",
        b"GX" => "Commodore",
        b"GY" => "The Game Factory",
        b"GZ" => "Gammick Entertainment",
        b"H3" => "Zen United",
        b"H4" => "SNK Playmore",
        b"HA" => "Nobilis",
        b"HE" => "Gust",
        b"HF" => "Level-5",
        b"HG" => "Graffiti Entertainment",
        b"HH" => "Focus Home Interactive",
        b"HJ" => "Genius Products",
        b"HK" => "D2C Games",
        b"HL" => "Frontier Developments",
        b"HM" => "HMH Interactive",
        b"HN" => "High Voltage Software",
        b"HQ" => "Abstraction Games",
        b"HS" => "Tru Blu",
        b"HT" => "Big Blue Bubble",
        b"HU" => "Ghostfire Games",
        b"HW" => "Incredible Technologies",
        b"HY" => "Reef Entertainment",
        b"HZ" => "Nordcurrent",
        b"J8" => "D4 Enterprise",
        b"J9" => "AQ Interactive",
        b"JD" => "SKONEC Entertainment",
        b"JE" => "E Frontier",
        b"JF" => "Arc System Works",
        b"JG" => "The Games Company",
        b"JH" => "City Interactive",
        b"JJ" => "Deep Silver",
        b"JP" => "redspotgames",
        b"JR" => "Engine Software",
        b"JS" => "Digital Leisure",
        b"JT" => "Empty Clip Studios",
        b"JU" => "Riverman Media",
        b"JV" => "JV Games",
        b"JW" => "BigBen Interactive",
        b"JX" => "Shin'en Multimedia",
        b"JY" => "Steel Penny Games",
        b"JZ" => "505 Games",
        b"K2" => "Coca-Cola (Japan) Company",
        b"K3" => "Yudo",
        b"K6" => "Nihon System",
        b"KB" => "Nippon Ichi Software",
        b"KG" => "Kando Games",
        b"KH" => "Joju Games",
        b"KJ" => "Studio Zan",
        b"KK" => "DK Games",
        b"KL" => "Abylight",
        b"KM" => "Deep Silver",
        b"KN" => "Gameshastra",
        b"KP" => "Purple Hills",
        b"KQ" => "Over the Top Games",
        b"KR" => "KREA Medie",
        b"KT" => "The Code Monkeys",
        b"KW" => "Semnat Studios",
        b"KY" => "Medaverse Studios",
        b"L3" => "G-Mode",
        b"L8" => "FujiSoft",
        b"LB" => "Tryfirst",
        b"LD" => "Studio Zan",
        b"LF" => "Kemco",
        b"LG" => "Black Bean Games",
        b"LJ" => "Legendo Entertainment",
        b"LL" => "HB Studios",
        b"LN" => "GameOn",
        b"LP" => "Left Field Productions",
        b"LR" => "Koch Media",
        b"LT" => "Legacy Interactive",
        b"LU" => "Lexis Numerique",
        b"LW" => "Grendel Games",
        b"LY" => "Icon Games / Super Icon",
        b"M0" => "Studio Zan",
        b"M1" => "Grand Prix Games",
        b"M2" => "HomeMedia",
        b"M4" => "Cybird",
        b"M6" => "Perpetuum",
        b"MB" => "Agenda",
        b"MD" => "Ateam",
        b"ME" => "Silver Star Japan",
        b"MF" => "Yamasa",
        b"MH" => "Mentor Interactive",
        b"MJ" => "Mumbo Jumbo",
        b"ML" => "DTP Young Entertainment",
        b"MM" => "Big John Games",
        b"MN" => "Mindscape",
        b"MR" => "Mindscape",
        b"MS" => "Milestone / UFO Interactive Games",
        b"MT" => "Blast! Entertainment",
        b"MV" => "Marvelous Entertainment",
        b"MZ" => "Mad Catz",
        b"N0" => "Exkee",
        b"N4" => "Zoom",
        b"N7" => "T&S",
        b"N9" => "Tera Box",
        b"NA" => "Tom Create",
        b"NB" => "HI Games & Publishing",
        b"NE" => "Kosaido",
        b"NF" => "Peakvox",
        b"NG" => "Nordic Games",
        b"NH" => "Gevo Entertainment",
        b"NJ" => "Enjoy Gaming",
        b"NK" => "Neko Entertainment",
        b"NL" => "Nordic Softsales",
        b"NN" => "Nnooo",
        b"NP" => "Nobilis",
        b"NQ" => "Namco Bandai Partners",
        b"NR" => "Destineer Publishing / Bold Games",
        b"NS" => "Nippon Ichi Software America",
        b"NT" => "Nocturnal Entertainment",
        b"NV" => "Nicalis",
        b"NW" => "Deep Fried Entertainment",
        b"NX" => "Barnstorm Games",
        b"NY" => "Nicalis",
        b"P1" => "Poisoft",
        b"PH" => "Playful Entertainment",
        b"PK" => "Knowledge Adventure",
        b"PL" => "Playlogic Entertainment",
        b"PM" => "Warner Bros. Interactive Entertainment",
        b"PN" => "P2 Games",
        b"PQ" => "PopCap Games",
        b"PS" => "Bplus",
        b"PT" => "Firemint",
        b"PU" => "Pub Company",
        b"PV" => "Pan Vision",
        b"PY" => "Playstos Entertainment",
        b"PZ" => "GameMill Publishing",
        b"Q2" => "Santa Entertainment",
        b"Q3" => "Asterizm",
        b"Q4" => "Hamster",
        b"Q5" => "Recom",
        b"QA" => "Miracle Kidz",
        b"QC" => "Kadokawa Shoten / Enterbrain",
        b"QH" => "Virtual Play Games",
        b"QK" => "MACHINE Studios",
        b"QM" => "Object Vision Software",
        b"QQ" => "Gamelion",
        b"QR" => "Lapland Studio",
        b"QT" => "CALARIS",
        b"QU" => "QubicGames",
        b"QV" => "Ludia",
        b"QW" => "Kaasa Solution",
        b"QX" => "Press Play",
        b"QZ" => "Hands-On Mobile",
        b"RA" => "Office Create",
        b"RG" => "Ronimo Games",
        b"RH" => "h2f Games",
        b"RM" => "Rondomedia",
        b"RN" => "Mastiff / N3V Games",
        b"RQ" => "GolemLabs & Zoozen",
        b"RS" => "Brash Entertainment",
        b"RT" => "RTL Enterprises",
        b"RV" => "bitComposer Games",
        b"RW" => "RealArcade",
        b"RX" => "Reflexive Entertainment",
        b"RZ" => "Akaoni Studio",
        b"S5" => "SouthPeak Games",
        b"SH" => "Sabarasa",
        b"SJ" => "Cosmonaut Games",
        b"SP" => "Blade Interactive Studios",
        b"SQ" => "Sonalysts",
        b"SR" => "SnapDragon Games",
        b"SS" => "Sanuk Games",
        b"ST" => "Stickmen Studios",
        b"SU" => "Slitherine",
        b"SV" => "SevenOne Intermedia",
        b"SZ" => "Storm City Games",
        b"TH" => "Kolkom",
        b"TJ" => "Broken Rules",
        b"TL" => "Telltale Games",
        b"TR" => "Tetris Online",
        b"TS" => "Triangle Studios",
        b"TV" => "Tivola",
        b"TW" => "Two Tribes",
        b"TY" => "Teyon",
        b"UG" => "Data Design Interactive / Popcorn Arcade / Metro 3D",
        b"UH" => "Intenium Console",
        b"UJ" => "Ghostlight",
        b"UK" => "iFun4all",
        b"UN" => "Chillingo",
        b"UP" => "EnjoyUp Games",
        b"UR" => "Sudden Games",
        b"US" => "USM",
        b"UU" => "Onteca",
        b"UV" => "Fugazo",
        b"UW" => "Coresoft",
        b"VG" => "Vogster Entertainment",
        b"VK" => "Sandlot Games",
        b"VL" => "Eko Software",
        b"VN" => "Valcon Games",
        b"VP" => "Virgin Play",
        b"VS" => "Korner Entertainment",
        b"VT" => "Microforum Games",
        b"VU" => "Double Jungle",
        b"VV" => "Pixonauts",
        b"VX" => "Frontline Studios",
        b"VZ" => "Little Orbit",
        b"WD" => "Amazon",
        b"WG" => "2D Boy",
        b"WH" => "NinjaBee",
        b"WJ" => "Studio Walljump",
        b"WL" => "Wired Productions",
        b"WN" => "tons of bits",
        b"WP" => "White Park Bay Software",
        b"WQ" => "Revistronic",
        b"WR" => "Warner Bros. Interactive Entertainment",
        b"WS" => "MonkeyPaw Games",
        b"WW" => "Slang Publishing",
        b"WY" => "WayForward Technologies",
        b"WZ" => "Wizarbox",
        b"X0" => "SDP Games",
        b"X3" => "CK Games",
        b"X4" => "Easy Interactive",
        b"XB" => "Hulu",
        b"XG" => "XGen Studios",
        b"XJ" => "XSEED Games",
        b"XK" => "Exkee",
        b"XM" => "DreamBox Games",
        b"XN" => "Netflix",
        b"XS" => "Aksys Games",
        b"XT" => "Funbox Media",
        b"XU" => "Shanblue Interactive",
        b"XV" => "Keystone Game Studio",
        b"XW" => "Lemon Games",
        b"XY" => "Gaijin Games",
        b"Y1" => "Tubby Games",
        b"Y5" => "Easy Interactive",
        b"Y6" => "Motiviti",
        b"Y7" => "The Learning Company",
        b"Y9" => "RadiationBurn",
        b"YC" => "NECA",
        b"YD" => "Infinite Dreams",
        b"YF" => "O2 Games",
        b"YG" => "Maximum Family Games",
        b"YJ" => "Frozen Codebase",
        b"YK" => "MAD Multimedia",
        b"YN" => "Game Factory",
        b"YS" => "Yullaby",
        b"YT" => "Corecell Technology",
        b"YV" => "KnapNok Games",
        b"YX" => "Selectsoft",
        b"YY" => "FDG Entertainment",
        b"Z4" => "Ntreev Soft",
        b"Z5" => "Shinsegae I&C",
        b"ZA" => "WBA Interactive",
        b"ZG" => "Zallag",
        b"ZH" => "Internal Engine",
        b"ZJ" => "Performance Designed Products",
        b"ZK" => "Anima Game Studio",
        b"ZP" => "Fishing Cactus",
        b"ZS" => "Zinkia Entertainment",
        b"ZV" => "RedLynx",
        b"ZW" => "Judo Baby",
        b"ZX" => "TopWare Interactive",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nintendo_codes_resolve() {
        assert_eq!(lookup_maker("01"), Some("Nintendo"));
        assert_eq!(lookup_maker("02"), Some("Nintendo"));
    }

    #[test]
    fn lookup_is_case_insensitive() {
        assert_eq!(lookup_maker("af"), Some("Namco Bandai Games"));
        assert_eq!(lookup_maker("AF"), Some("Namco Bandai Games"));
        assert_eq!(lookup_maker("aF"), Some("Namco Bandai Games"));
    }

    #[test]
    fn unmapped_returns_none() {
        assert_eq!(lookup_maker("00"), None);
        assert_eq!(lookup_maker("ZZ"), None);
    }

    #[test]
    fn wrong_length_returns_none() {
        assert_eq!(lookup_maker(""), None);
        assert_eq!(lookup_maker("A"), None);
        assert_eq!(lookup_maker("ABC"), None);
    }

    #[test]
    fn common_publishers() {
        assert_eq!(lookup_maker("08"), Some("Capcom"));
        assert_eq!(lookup_maker("4F"), Some("Eidos Interactive"));
        assert_eq!(lookup_maker("69"), Some("Electronic Arts"));
        assert_eq!(lookup_maker("A4"), Some("Konami"));
    }
}
