name: "Build CLI for Commit"

on:
  pull_request:
  push:
    branches: [ "develop" ]
    paths:
      - crates/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/build-cli.yml
      - .github/workflows/_build-cli.yml

jobs:
  build-cli:
    uses: ./.github/workflows/_build-cli.yml
    secrets: inherit
