name: "Build GUI for Commit"

on:
  pull_request:
  push:
    branches: [ "develop" ]
    paths:
      - crates/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/build-gui.yml
      - .github/workflows/_build-gui.yml

jobs:
  build-gui:
    uses: ./.github/workflows/_build-gui.yml
    secrets: inherit
