name: Create Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog:
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@469f0e5e35831fbd1962706f29f65daf0a5723f2 # v6.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "./Cargo.toml"
          version-path: "workspace.package.version"
          pre-commit: ".github/scripts/pre-commit.js"
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  build-cli:
    needs: changelog
    permissions:
      contents: write
      id-token: write
      attestations: write
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/_build-cli.yml
    with:
      ref: ${{ needs.changelog.outputs.tag }}
      release: true
      release_tag: ${{ needs.changelog.outputs.tag }}
    secrets: inherit

  build-ffi:
    needs: changelog
    permissions:
      contents: write
      id-token: write
      attestations: write
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/_build-ffi.yml
    with:
      ref: ${{ needs.changelog.outputs.tag }}
      release: true
      release_tag: ${{ needs.changelog.outputs.tag }}
    secrets: inherit

  build-gui:
    needs: changelog
    permissions:
      contents: write
      id-token: write
      attestations: write
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/_build-gui.yml
    with:
      ref: ${{ needs.changelog.outputs.tag }}
      release: true
      release_tag: ${{ needs.changelog.outputs.tag }}
    secrets: inherit
