name: Create Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog:
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v6
      - name: Create Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './Cargo.toml'
          version-path: "workspace.package.version"
          pre-commit: '.github/scripts/pre-commit.js'
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  build-cli:
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/_build-cli.yml
    with:
      ref: ${{ needs.changelog.outputs.tag }}
      release: true
      release_tag: ${{ needs.changelog.outputs.tag }}
    secrets: inherit

  build-gui:
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    uses: ./.github/workflows/_build-gui.yml
    with:
      ref: ${{ needs.changelog.outputs.tag }}
      release: true
      release_tag: ${{ needs.changelog.outputs.tag }}
    secrets: inherit
